=== DawidLoubser/reference/resources/information/technologies/xml/xsl-transform/examples/periodicTableSimplification/toOtherFormat-schema/periodicMinimal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:p="urn:physics:elements"
    targetNamespace="urn:physics:elements"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    
    <xs:annotation><xs:documentation>
        This schema contains types which could be used to construct
        a minimal, but strict, periodic table of the elements.
    </xs:documentation></xs:annotation>
    
    <xs:complexType name="Element">
        <xs:annotation><xs:documentation>
            A minimal representation of a periodic element, including its
            state at room temperature or ('natural state'), assumed as
            a temperature of 300 Kelvin.
        </xs:documentation></xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="symbol" type="p:AtomicSymbol"/>
            <xs:element name="atomicNumber" type="xs:positiveInteger"/>
            <xs:element name="atomicWeight" type="xs:decimal" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="naturalState" type="p:MaterialState" use="optional"/>
    </xs:complexType>
        
    <xs:complexType name="CollectionOfElements">
        <xs:annotation><xs:documentation>
            A sequence of elements that could represent a periodic table
        </xs:documentation></xs:annotation>
        <xs:sequence>
            <xs:element name="element" type="p:Element" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:simpleType name="MaterialState">
        <xs:annotation><xs:documentation>
            The state of an element: 'gas', 'liquid' or 'solid'.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="gas"/>
            <xs:enumeration value="liquid"/>
            <xs:enumeration value="solid"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="AtomicSymbol">
        <xs:annotation><xs:documentation>
            The symbol of an element, e.g. 'Al' or 'H'.
        </xs:documentation></xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]{0,2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="periodicTable" type="p:CollectionOfElements">
        <xs:annotation><xs:documentation>
            A periodic table of elements
        </xs:documentation></xs:annotation>
    </xs:element>
</xs:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/xsl-transform/examples/periodicTableSimplification/toOtherFormat-schema/output.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="periodicMinimal.css"?>
<!--This simplification automatically produced with XSLT-->
<p:periodicTable xmlns:p="urn:physics:elements"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="urn:physics:elements periodicMinimal.xsd">
    <p:element naturalState="gas">
        <p:name>Hydrogen</p:name>
        <p:symbol>H</p:symbol>
        <p:atomicNumber>1</p:atomicNumber>
        <p:atomicWeight>1.00794</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Helium</p:name>
        <p:symbol>He</p:symbol>
        <p:atomicNumber>2</p:atomicNumber>
        <p:atomicWeight>4.0026</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Lithium</p:name>
        <p:symbol>Li</p:symbol>
        <p:atomicNumber>3</p:atomicNumber>
        <p:atomicWeight>6.941</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Beryllium</p:name>
        <p:symbol>Be</p:symbol>
        <p:atomicNumber>4</p:atomicNumber>
        <p:atomicWeight>9.01218</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Boron</p:name>
        <p:symbol>B</p:symbol>
        <p:atomicNumber>5</p:atomicNumber>
        <p:atomicWeight>10.811</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Carbon</p:name>
        <p:symbol>C</p:symbol>
        <p:atomicNumber>6</p:atomicNumber>
        <p:atomicWeight>12.011</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Nitrogen</p:name>
        <p:symbol>N</p:symbol>
        <p:atomicNumber>7</p:atomicNumber>
        <p:atomicWeight>14.0067</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Oxygen</p:name>
        <p:symbol>O</p:symbol>
        <p:atomicNumber>8</p:atomicNumber>
        <p:atomicWeight>15.9994</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Fluorine</p:name>
        <p:symbol>F</p:symbol>
        <p:atomicNumber>9</p:atomicNumber>
        <p:atomicWeight>18.9984</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Neon</p:name>
        <p:symbol>Ne</p:symbol>
        <p:atomicNumber>10</p:atomicNumber>
        <p:atomicWeight>20.1797</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Sodium</p:name>
        <p:symbol>Na</p:symbol>
        <p:atomicNumber>11</p:atomicNumber>
        <p:atomicWeight>22.98977</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Magnesium</p:name>
        <p:symbol>Mg</p:symbol>
        <p:atomicNumber>12</p:atomicNumber>
        <p:atomicWeight>24.305</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Aluminum</p:name>
        <p:symbol>Al</p:symbol>
        <p:atomicNumber>13</p:atomicNumber>
        <p:atomicWeight>26.98154</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Silicon</p:name>
        <p:symbol>Si</p:symbol>
        <p:atomicNumber>14</p:atomicNumber>
        <p:atomicWeight>28.0855</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Phosphorus</p:name>
        <p:symbol>P</p:symbol>
        <p:atomicNumber>15</p:atomicNumber>
        <p:atomicWeight>30.97376</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Sulfur</p:name>
        <p:symbol>S</p:symbol>
        <p:atomicNumber>16</p:atomicNumber>
        <p:atomicWeight>32.066</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Chlorine</p:name>
        <p:symbol>Cl</p:symbol>
        <p:atomicNumber>17</p:atomicNumber>
        <p:atomicWeight>35.4527</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Argon</p:name>
        <p:symbol>Ar</p:symbol>
        <p:atomicNumber>18</p:atomicNumber>
        <p:atomicWeight>39.948</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Potassium</p:name>
        <p:symbol>K</p:symbol>
        <p:atomicNumber>19</p:atomicNumber>
        <p:atomicWeight>39.0983</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Calcium</p:name>
        <p:symbol>Ca</p:symbol>
        <p:atomicNumber>20</p:atomicNumber>
        <p:atomicWeight>40.078</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Scandium</p:name>
        <p:symbol>Sc</p:symbol>
        <p:atomicNumber>21</p:atomicNumber>
        <p:atomicWeight>44.9559</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Titanium</p:name>
        <p:symbol>Ti</p:symbol>
        <p:atomicNumber>22</p:atomicNumber>
        <p:atomicWeight>47.88</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Vanadium</p:name>
        <p:symbol>V</p:symbol>
        <p:atomicNumber>23</p:atomicNumber>
        <p:atomicWeight>50.9415</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Chromium</p:name>
        <p:symbol>Cr</p:symbol>
        <p:atomicNumber>24</p:atomicNumber>
        <p:atomicWeight>51.996</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Manganese</p:name>
        <p:symbol>Mn</p:symbol>
        <p:atomicNumber>25</p:atomicNumber>
        <p:atomicWeight>54.938</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Iron</p:name>
        <p:symbol>Fe</p:symbol>
        <p:atomicNumber>26</p:atomicNumber>
        <p:atomicWeight>55.847</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Cobalt</p:name>
        <p:symbol>Co</p:symbol>
        <p:atomicNumber>27</p:atomicNumber>
        <p:atomicWeight>58.9332</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Nickel</p:name>
        <p:symbol>Ni</p:symbol>
        <p:atomicNumber>28</p:atomicNumber>
        <p:atomicWeight>58.6934</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Copper</p:name>
        <p:symbol>Cu</p:symbol>
        <p:atomicNumber>29</p:atomicNumber>
        <p:atomicWeight>63.546</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Zinc</p:name>
        <p:symbol>Zn</p:symbol>
        <p:atomicNumber>30</p:atomicNumber>
        <p:atomicWeight>65.39</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Gallium</p:name>
        <p:symbol>Ga</p:symbol>
        <p:atomicNumber>31</p:atomicNumber>
        <p:atomicWeight>69.723</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Germanium</p:name>
        <p:symbol>Ge</p:symbol>
        <p:atomicNumber>32</p:atomicNumber>
        <p:atomicWeight>72.61</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Arsenic</p:name>
        <p:symbol>As</p:symbol>
        <p:atomicNumber>33</p:atomicNumber>
        <p:atomicWeight>74.9216</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Selenium</p:name>
        <p:symbol>Se</p:symbol>
        <p:atomicNumber>34</p:atomicNumber>
        <p:atomicWeight>78.96</p:atomicWeight>
    </p:element>
    <p:element naturalState="liquid">
        <p:name>Bromine</p:name>
        <p:symbol>Br</p:symbol>
        <p:atomicNumber>35</p:atomicNumber>
        <p:atomicWeight>79.904</p:atomicWeight>
    </p:element>
    <p:element naturalState="gas">
        <p:name>Krypton</p:name>
        <p:symbol>Kr</p:symbol>
        <p:atomicNumber>36</p:atomicNumber>
        <p:atomicWeight>83.8</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Rubidium</p:name>
        <p:symbol>Rb</p:symbol>
        <p:atomicNumber>37</p:atomicNumber>
        <p:atomicWeight>85.4678</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Strontium</p:name>
        <p:symbol>Sr</p:symbol>
        <p:atomicNumber>38</p:atomicNumber>
        <p:atomicWeight>87.62</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Yttrium</p:name>
        <p:symbol>Y</p:symbol>
        <p:atomicNumber>39</p:atomicNumber>
        <p:atomicWeight>88.9059</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Zirconium</p:name>
        <p:symbol>Zr</p:symbol>
        <p:atomicNumber>40</p:atomicNumber>
        <p:atomicWeight>91.224</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Niobium</p:name>
        <p:symbol>Nb</p:symbol>
        <p:atomicNumber>41</p:atomicNumber>
        <p:atomicWeight>92.9064</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Molybdenum</p:name>
        <p:symbol>Mo</p:symbol>
        <p:atomicNumber>42</p:atomicNumber>
        <p:atomicWeight>95.94</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Technetium</p:name>
        <p:symbol>Tc</p:symbol>
        <p:atomicNumber>43</p:atomicNumber>
        <p:atomicWeight>98</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Ruthenium</p:name>
        <p:symbol>Ru</p:symbol>
        <p:atomicNumber>44</p:atomicNumber>
        <p:atomicWeight>101.07</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Rhodium</p:name>
        <p:symbol>Rh</p:symbol>
        <p:atomicNumber>45</p:atomicNumber>
        <p:atomicWeight>102.9055</p:atomicWeight>
    </p:element>
    <p:element naturalState="solid">
        <p:name>Palladium</p:name>
        <p:symbol>Pd</p:symbol>
        <p:atomicNumber>46</p:atomicNumber>
        <p:atomicWeight>106.42</p:atomicWeight>
