=== DawidLoubser/reference/resources/information/technologies/xml/schemas/specialization/src/abstractType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.solms.co.za/clients"
    xmlns="http://www.solms.co.za/clients" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified">
    
  <xs:element name="client" type="Client"/>
  
  <xs:complexType name="Client">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="account" type="Account" 
                 maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Account" abstract="true">
    <xs:sequence>
      <xs:element name="balance" type="xs:decimal"/>
      <xs:element name="accountNo" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="CreditCardAccount">
    <xs:complexContent>
      <xs:extension base="Account">
        <xs:sequence>
          <xs:element name="expiryDate" type="xs:date"/>
          <xs:element name="issuer" type="xs:string"/>
        </xs:sequence>          
        <xs:attribute name="type" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="ChequeAccount">
    <xs:complexContent>
      <xs:extension base="Account">
        <xs:sequence>
          <xs:element name="chequeFee" type="xs:decimal"/>
          <xs:element name="overdraftLimit" type="xs:decimal"/>
        </xs:sequence>          
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
   
</xs:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/schemas/specialization/src/abstractType.xml
<?xml version="1.0" encoding="UTF-8"?>
<client xmlns="http://www.solms.co.za/clients"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.solms.co.za/clients abstractType.xsd">
  <name>Jack</name>
  <account xsi:type="ChequeAccount">
    <balance>6542</balance>
    <accountNo>2765</accountNo>
    <chequeFee>23.34</chequeFee>
    <overdraftLimit>5000</overdraftLimit>
  </account>
  <account xsi:type="CreditCardAccount" type="MASTER">
    <balance>222</balance>
    <accountNo>235324</accountNo>
    <expiryDate>2006-10-10</expiryDate>
    <issuer>FNB</issuer>
  </account>
  
</client>
