=== DawidLoubser/reference/resources/information/technologies/xml/schemas/specialization/src/persons.xsd
<?xml version="1.0" encoding="UTF-8"?>  
<schema targetNamespace="http://www.SAA.com/passportControl/persons"
    xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:pass="http://www.SAA.com/passportControl/persons"
    elementFormDefault="qualified">

  <annotation>
    <documentation>Persons and employees</documentation>
  </annotation>
     
  <element name="persons">
    <complexType>
      <sequence>
        <element name="person" type="pass:Person" 
                       maxOccurs="unbounded"/>
        <element name="employee" type="pass:Employee" 
                       minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>  
  
  <complexType name="Person">
    <sequence>
      <element name="name" type="string"/>
      <element name="passport">
        <complexType>
          <sequence>
            <element name="country" type="string"/>
            <element name="passportNumber" type="string"/>
          </sequence>
        </complexType>
      </element>
    </sequence>
  </complexType>  
  
  <complexType name="Employee">
     <complexContent>
      <extension base="pass:Person">
        <sequence>
          <element name="employer" type="string"/>
                     <element name="salary" type="decimal"/>
        </sequence>
        <attribute name="permanent" 
            type="boolean" use="required"/>
      </extension>
    </complexContent>
  </complexType>
  
</schema>

=== DawidLoubser/reference/resources/information/technologies/xml/schemas/specialization/src/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<persons xmlns="http://www.SAA.com/passportControl/persons"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.SAA.com/passportControl/persons 
              persons.xsd">
  <person>
    <name>Piet Pompies</name>
    <passport>
      <country>South Africa</country>
      <passportNumber>RSA9873288763</passportNumber>
    </passport>
  </person>
  <person>
    <name>Tandi Mkondo</name>
    <passport>
      <country>South Africa</country>
      <passportNumber>RSA53278632876</passportNumber>
    </passport>
  </person>
  <employee permanent="true">
    <name>Marie Curie</name>
    <passport>
      <country>France</country>
      <passportNumber>FR7653276532765</passportNumber>
    </passport>
    <employer>University of X</employer>
    <salary>0</salary>
  </employee>
  
</persons>
