=== DawidLoubser/reference/resources/information/technologies/xml/schemas/uniquenessConstraints/src/partsCatalogMultiFieldIds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:element name="partsCatalog">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="parts" type="Parts">
          <xs:unique name="partID">
            <!-- Part must be unique based on combination of
              'id' attribute and 'manufacturer' sub-element -->
            <xs:selector xpath="part"/>
            <xs:field xpath="@id"/>
            <xs:field xpath="manufacturer"/>
          </xs:unique>
        </xs:element>

        <xs:element name="manufacturers" type="Manufacturers">
          <xs:unique name="manufacturerID">
            <!-- Manufacturer must be unique based on 'id' attribute -->
            <xs:selector xpath="manufacturer"/>
            <xs:field xpath="@id"/>
          </xs:unique>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Parts">
    <xs:sequence>
      <xs:element name="part" type="Part" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Manufacturers">
    <xs:sequence>
      <xs:element name="manufacturer" type="Manufacturer"
        maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Part">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="price" type="xs:decimal"/>
      <xs:element name="manufacturer" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer"/>
  </xs:complexType>

  <xs:complexType name="Manufacturer">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer"/>
  </xs:complexType>

</xs:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/schemas/uniquenessConstraints/src/partsCatalogMultiFieldIds.xml
<?xml version="1.0" encoding="UTF-8"?>
<partsCatalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="partsCatalogMultiFieldIds.xsd">

  <parts>

    <part id="121">
      <name>Screw</name>
      <price>12.40</price>
      <manufacturer>8</manufacturer>
    </part>

    <part id="121">
      <name>Nut</name>
      <price>4.40</price>
      <manufacturer>9</manufacturer>
    </part>

    <part id="122">
      <name>Bolt</name>
      <price>4.40</price>
      <manufacturer>7</manufacturer>
    </part>

  </parts>

  <manufacturers>

    <manufacturer id="7">
      <name>Screw Loose</name>
    </manufacturer>

    <manufacturer id="8">
      <name>Screws Loose</name>
    </manufacturer>

  </manufacturers>
</partsCatalog>
