=== DawidLoubser/reference/resources/information/technologies/xml/umlMapping/classDiagrams/specialization/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.solms.co.za/finance/accounts"
    xmlns="http://www.solms.co.za/finance/accounts"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:complexType name="Accounts">
        <xs:sequence>
            <xs:element name="account" type="Account" 
                minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Account" abstract="true">
        <xs:sequence>
            <xs:element name="accountNumber" type="xs:string"/>
            <xs:element name="balance" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CreditCardAccount">
        <xs:complexContent>
            <xs:extension base="Account">
                <xs:sequence>
                    <xs:element name="creditLimit" type="xs:decimal"/>
                    <xs:element name="creditCard" type="CreditCard"
                        minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="SavingsAccount">
        <xs:complexContent>
            <xs:extension base="Account">
                <xs:sequence>
                    <xs:element name="interestRate" type="xs:decimal"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="CreditCard">
        <xs:sequence>
            <xs:element name="cardNumber" type="xs:string"/>
            <xs:element name="clearingHouse" type="xs:string"/>
            <xs:element name="holderName" type="xs:string"/>
            <xs:element name="expiryDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="accounts" type="Accounts"/>
    
</xs:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/umlMapping/classDiagrams/specialization/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<accounts xmlns="http://www.solms.co.za/finance/accounts"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.solms.co.za/finance/accounts ./accounts.xsd">
    
    <account xsi:type="SavingsAccount">
        <accountNumber>S111</accountNumber>
        <balance>100</balance>
        <interestRate>4.3</interestRate>
    </account>
    
    <account xsi:type="CreditCardAccount">
        <accountNumber>CC121</accountNumber>
        <balance>345</balance>
        <creditLimit>1000</creditLimit>
        <creditCard>
            <cardNumber>4444 5555 3333 2221</cardNumber>
            <clearingHouse>AllClear</clearingHouse>
            <holderName>John Smith</holderName>
            <expiryDate>2010-01-02</expiryDate>
        </creditCard>
        <creditCard>
            <cardNumber>4444 5555 3333 2222</cardNumber>
            <clearingHouse>AllClear</clearingHouse>
            <holderName>Tandi Smith</holderName>
            <expiryDate>2010-01-02</expiryDate>
        </creditCard>
    </account>
    
    <account xsi:type="SavingsAccount">
        <accountNumber>S112</accountNumber>
        <balance>15000</balance>
        <interestRate>5.1</interestRate>
    </account>
    
</accounts>
