=== DawidLoubser/reference/resources/information/technologies/xml/schemas/simpleExample/src/travelLog.dtd
<!ELEMENT travelLog (trip+)>

<!ELEMENT trip (from, to, start, end, odoMeterStart, odoMeterEnd)>

<!ELEMENT from          (#PCDATA)>
<!ELEMENT to            (#PCDATA)>
<!ELEMENT start         (#PCDATA)>
<!ELEMENT end           (#PCDATA)>
<!ELEMENT odoMeterStart (#PCDATA)>
<!ELEMENT odoMeterEnd   (#PCDATA)>

=== DawidLoubser/reference/resources/information/technologies/xml/DTD/travelLog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Solms Training & Consulting: Simple Example -->
<!DOCTYPE travelLog SYSTEM "travellog.dtd">

<travelLog>
  <trip>
    <from>Kensington</from>
    <to>Johannesburg Airport</to>
    <start>15-2-2001 11:30</start>
    <end>15-2-2001 12:00</end>
    <odoMeterStart>22345</odoMeterStart>
    <odoMeterEnd>22375</odoMeterEnd>
  </trip>
  <trip>
    <from>Johannesburg Airport</from>
    <to>Rosebank Mall</to>
    <start>15-2-2001 12:35</start>
    <end>15-2-2001 13:15</end>
    <odoMeterStart>22375</odoMeterStart>
    <odoMeterEnd>22403</odoMeterEnd>
  </trip>
</travelLog>
