=== DawidLoubser/reference/resources/information/technologies/xml/schemas/namespaces/src/clientContactsNamespace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="myTargetNameSpaceName"
    xmlns:t="myTargetNameSpaceName" 
    elementFormDefault="qualified" attributeFormDefault="unqualified">
    
  <xs:complexType name="Client">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="contact" type="t:Contact"/>
    </xs:sequence>  
  </xs:complexType>
  
  <xs:complexType name="Contact">
    <xs:sequence>
      <xs:element name="telNo" type="xs:string"/>
      <xs:element name="eMail" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Clients">
    <xs:sequence>
      <xs:element name="client" type="t:Client" 
                         maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="clients" type="t:Clients"/>

</xs:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/schemas/namespaces/src/clientContactsNamespace.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns="myTargetNameSpaceName" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="myTargetNameSpaceName clientContactsNamespace.xsd">
   
  <client>
    <name>Jack</name>
    <contact>
      <telNo>011 726 4860</telNo>
      <eMail>Jack@Jill.org.za</eMail>
    </contact>
  </client>
     
  <client>
    <name>Jill</name>
    <contact>
      <telNo>011 726 4860</telNo>
      <eMail>Jill@Jack.org.za</eMail>
    </contact>
  </client>
  
</clients>
