=== DawidLoubser/reference/resources/information/technologies/xml/DTD/Contacts.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Solms Training & Consulting: Contacts.xml) -->

<!ELEMENT Contacts (Contact+)>

<!ELEMENT Contact (surName, firstName+, telNo*, eMailNo?, (idNo | passportNo))>

<!ELEMENT surName (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT telNo (#PCDATA)>
<!ELEMENT eMailNo (#PCDATA)>
<!ELEMENT idNo (#PCDATA)>
<!ELEMENT passportNo (#PCDATA)>

=== DawidLoubser/reference/resources/information/technologies/xml/Parsers/Contacts.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Solms Training & Consulting: Contacts.xml  -->

<!DOCTYPE Contacts SYSTEM "Contacts.dtd">

<Contacts>
	<Contact>
		<surName>Pompies</surName>
		<firstName>Piet</firstName>
		<idNo>365437654</idNo>
	</Contact>
	<Contact>
		<surName>the Ripper</surName>
		<firstName>Jack</firstName>
		<telNo>6542654123</telNo>
		<telNo>6543125433</telNo>
		<eMailNo>RipperJack@SteetsOfLondon.com</eMailNo>
		<idNo>070780705</idNo>
	</Contact>
	<Contact>
		<surName>Bach</surName>
		<firstName>Johannes</firstName>
		<firstName>Sebastian</firstName>
		<passportNo>1685-1750</passportNo>
	</Contact>
</Contacts>
