=== DawidLoubser/reference/resources/information/technologies/xml/DTD/TrainingInstitution.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TrainingInstitution (Presentation+, Lecturer+, Course+, Venue+)>

<!ELEMENT Presentation (#PCDATA | period)>

<!ATTLIST Presentation
  course IDREF #REQUIRED
  lecturer IDREF #REQUIRED
  venue IDREF #REQUIRED>
  
<!ELEMENT Venue (name)>

<!ATTLIST Venue
  registeredName ID #REQUIRED>
  
<!ELEMENT period (startDate, endDate)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT Lecturer (name, telNo+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telNo (#PCDATA)>
<!ELEMENT Course (name)>

<!ATTLIST Course
  id ID #REQUIRED>
  
<!ATTLIST Lecturer
  id ID #REQUIRED>

=== DawidLoubser/reference/resources/information/technologies/xml/DTD/TrainingInstitution.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TrainingInstitution SYSTEM "TrainingInstitution.dtd">
<TrainingInstitution>
  <Presentation course="STC_05" lecturer="Lect01" venue="Emmy01">
    <period>
      <startDate>6-8-2001</startDate>
      <endDate>8-8-2001</endDate>
    </period>
  </Presentation>
  <Presentation course="STC_02" lecturer="Lect01" venue="Emmy01">
    <period>
      <startDate>17-9-2001</startDate>
      <endDate>21-9-2001</endDate>
    </period>
  </Presentation>
  <Lecturer id="Lect01">
    <name>Fritz</name>
    <telNo>+27 11 486 4270</telNo>
  </Lecturer>
  <Lecturer id="Lect02">
    <name>Tandi</name>
    <telNo>+27 11 486 4001</telNo>
  </Lecturer>
  <Course id="STC_05">
    <name>XML</name>
  </Course>
  <Course id="STC_02">
    <name>Object-Oriented Analysis and Design using UML</name>
  </Course>
  <Venue registeredName="Emmy01">
    <name>Emmarentia Gardens Training Centre</name>
  </Venue>
</TrainingInstitution>
