=== DawidLoubser/reference/resources/information/technologies/xml/schemas/simpleObjectGraphs/src/partsCatalog.xsd
<xsd:schema
  targetNamespace="http://www.ManufacturingUnlimited.co.za/partsCatalog"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.ManufacturingUnlimited.co.za/partsCatalog"
  elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xsd:complexType name="Part">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="description" type="xsd:string" minOccurs="0"/>
      <xsd:element name="assemblyInstruction" type="xsd:string"
        minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="part" type="Part" minOccurs="0"
        maxOccurs="unbounded"/>
      <xsd:element name="manufacturer" type="xsd:IDREF" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="code" type="xsd:ID"/>
  </xsd:complexType>

  <xsd:complexType name="Product">
    <xsd:complexContent>
      <xsd:extension base="Part">
        <xsd:sequence>
          <xsd:element name="price">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="amount" type="xsd:decimal"/>
                <xsd:element name="currency" type="xsd:string"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Manufacturer">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="address" type="xsd:string"/>
      <xsd:element name="part" type="xsd:IDREF" minOccurs="0"
        maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:ID"/>
  </xsd:complexType>

  <xsd:element name="partsCatalog">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="part" type="Part" maxOccurs="unbounded"/>
        <xsd:element name="manufacturer" type="Manufacturer"
          maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== DawidLoubser/reference/resources/information/technologies/xml/schemas/simpleObjectGraphs/src/partsCatalog.xml
<partsCatalog 
  xmlns="http://www.ManufacturingUnlimited.co.za/partsCatalog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.ManufacturingUnlimited.co.za/partsCatalog 
                                   partsCatalog.xsd">

  <part code="PC103">
    <name>Pentium Flyer</name>
    <description>Pentium III based PC</description>
    <assemblyInstruction>
      Plug keyboard cable into green socket.
    </assemblyInstruction>
    <assemblyInstruction>
      Plug rat (mouse) cable into purple socket.
    </assemblyInstruction>
    <assemblyInstruction>
      Plug screen cable into whatever hole it fits in.
    </assemblyInstruction>

    <part code="kbd03">
      <name>keyboard</name>
    </part>

    <part code="rat12">
      <name>rat</name>
      <manufacturer>Log002</manufacturer>
    </part>

    <part code="scr001">
      <name>screen</name>
    </part>

    <part>
      <name>processingBox</name>
      <part code="MB121">
        <name>motherboard</name>
        <part code="PIII-800">
          <name>CPU</name>
        </part>
      </part>
    </part>
  </part>

  <part xsi:type="Product">
    <name>Crunch-It</name>
    <description>The number crunching monster.</description>
    <part>
      <name>Cube processor array</name>
    </part>
    <price>
      <amount>33223.98</amount>
      <currency>ZAR</currency>
    </price>
  </part>

  <manufacturer id="Log002">
    <name>Logitech</name>
    <address>13 Cyber Street, Silicon Hill</address>
    <part>rat12</part>
    <part>MB121</part>
  </manufacturer>

</partsCatalog>
